sudo: required  # see https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install graphviz -y
language: python
python:
  - "3.5"  # I'm using a virtual environment with this version
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
script: pytest
notifications:
    email:
        on_success: change
        on_failure: always
